---
name: Merge
on:
  issue_comment:
    types:
      - created
jobs:
  merge:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    if: |
      github.event.issue.pull_request && github.event.comment.body == '/merge'
    permissions:
      pull-requests: write
    env:
      TARGET: foo
      GH_COMMENT_PR_NUMBER: ${{github.event.issue.number}}
    steps:
      - env:
          GITHUB_TOKEN: ${{github.token}}
          COMMENT_ID: ${{github.event.comment.id}}
        run: |
          body="/merge [workflow run]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$GITHUB_REPOSITORY/issues/comments/$COMMENT_ID" \
            -f "body=$body"

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
          permissions: >-
            {
              "contents": "write",
              "pull_requests": "write"
            }
          repositories: >-
            [
              "${{github.event.repository.name}}"
            ]

      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.42.2
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}

      - name: Dismiss self approvals
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}
        run: github-comment exec -- deny-self-approve -pr "$GH_COMMENT_PR_NUMBER" validate -d
      - name: Merge
        run: |
          github-comment exec -- gh pr merge "$GH_COMMENT_PR_NUMBER" -s
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}
